/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Kosarkas;
import domen.TipUcinka;
import domen.Ucinak;
import domen.Utakmica;
import forme.komponente.TblModelUcinak;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import komunikacija.KlijentKomunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;

/**
 *
 * @author Marko
 */
public class FrmDodajUcinak extends javax.swing.JDialog {

    Utakmica u;
    TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
    TransferObjekatOdgovor toOdgovor = new TransferObjekatOdgovor();

    /**
     * Creates new form FrmDodajUcinak
     */
    public FrmDodajUcinak(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //napuniComboe();
    }

    public FrmDodajUcinak(java.awt.Frame parent, boolean modal, Utakmica u) {
        super(parent, modal);
        initComponents();
        this.u = u;
        napuniComboe();
        napuniTabelu();
        pozicionirajFormu();
        jbtnSacuvaj.setEnabled(false);
        jbtnObrisiSve.setEnabled(false);
        jbtnObrišiJedan.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcomboIgrac = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jcomboTip = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jcomboVrednost = new javax.swing.JComboBox();
        jbtnDodaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUcinci = new javax.swing.JTable();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnObrišiJedan = new javax.swing.JButton();
        jbtnObrisiSve = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj učinak");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setText("Izaberite igrača: ");

        jcomboIgrac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Izaberite tip učinka:");

        jcomboTip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Izaberite vrednost učinka:");

        jcomboVrednost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnDodaj.setText("Dodaj");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        jtblUcinci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblUcinci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblUcinciMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblUcinci);

        jbtnSacuvaj.setText("Sačuvaj učinke");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jbtnObrišiJedan.setText("Obriši učinak");
        jbtnObrišiJedan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrišiJedanActionPerformed(evt);
            }
        });

        jbtnObrisiSve.setText("Obriši sve");
        jbtnObrisiSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiSveActionPerformed(evt);
            }
        });

        jbtnPlus.setText("+");
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnDodaj)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcomboTip, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcomboIgrac, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcomboVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDetalji))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtnObrišiJedan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnObrisiSve, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcomboIgrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcomboTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPlus)
                    .addComponent(jbtnDetalji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcomboVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnDodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnObrišiJedan)
                    .addComponent(jbtnObrisiSve))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
        Kosarkas k = (Kosarkas) jcomboIgrac.getSelectedItem();
        TipUcinka t = (TipUcinka) jcomboTip.getSelectedItem();
        int v = (int) jcomboVrednost.getSelectedItem();
        Ucinak ucinak = new Ucinak(k, u, t, v);
        TblModelUcinak tmu = (TblModelUcinak) jtblUcinci.getModel();
        tmu.dodajRed(ucinak);
        jbtnSacuvaj.setEnabled(true);
        jbtnObrisiSve.setEnabled(true);
    }//GEN-LAST:event_jbtnDodajActionPerformed

    private void jbtnObrišiJedanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrišiJedanActionPerformed
        int ucinak = jtblUcinci.getSelectedRow();
        TblModelUcinak tmu = (TblModelUcinak) jtblUcinci.getModel();
        tmu.obrisiRed(ucinak);
        if (jtblUcinci.getRowCount() == 0) {
            jbtnSacuvaj.setEnabled(false);
            jbtnObrisiSve.setEnabled(false);
            jbtnObrišiJedan.setEnabled(false);
        }
    }//GEN-LAST:event_jbtnObrišiJedanActionPerformed

    private void jbtnObrisiSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiSveActionPerformed
        TblModelUcinak tmu = (TblModelUcinak) jtblUcinci.getModel();
        tmu.isprazniListuUcinaka();
        jbtnObrisiSve.setEnabled(false);
        jbtnSacuvaj.setEnabled(false);
        jbtnObrišiJedan.setEnabled(false);
    }//GEN-LAST:event_jbtnObrisiSveActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        List<Ucinak> lista = ((TblModelUcinak) jtblUcinci.getModel()).getListaUcinaka();

        toZahtev.setOperacija(Konstante.SACUVAJ_LISTU_UCINAKA);
        toZahtev.setParametar(lista);
        KlijentKomunikacija.getInstance().posaljiZahtev(toZahtev);
        try {
            toOdgovor = KlijentKomunikacija.getInstance().primiOdgovor();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FrmDodajUcinak.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (toOdgovor.getIzuzetak() != null) {
            try {
                throw (Exception) toOdgovor.getIzuzetak();
            } catch (Exception ex) {
                Logger.getLogger(FrmLogovanje.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ((TblModelUcinak) jtblUcinci.getModel()).isprazniListuUcinaka();
        jbtnObrisiSve.setEnabled(false);
        jbtnObrišiJedan.setEnabled(false);
        jbtnSacuvaj.setEnabled(false);
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jtblUcinciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblUcinciMouseClicked
        jbtnObrišiJedan.setEnabled(jtblUcinci.getSelectedRow() > -1);
    }//GEN-LAST:event_jtblUcinciMouseClicked

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
        FrmDodajTipUcinka forma = new FrmDodajTipUcinka(null, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        FrmPregledTipovaUcinaka forma = new FrmPregledTipovaUcinaka(null, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        napuniComboZaTipove();
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        napuniComboZaTipove();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDodajUcinak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDodajUcinak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDodajUcinak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDodajUcinak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDodajUcinak dialog = new FrmDodajUcinak(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnDodaj;
    private javax.swing.JButton jbtnObrisiSve;
    private javax.swing.JButton jbtnObrišiJedan;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcomboIgrac;
    private javax.swing.JComboBox jcomboTip;
    private javax.swing.JComboBox jcomboVrednost;
    private javax.swing.JTable jtblUcinci;
    // End of variables declaration//GEN-END:variables

    private void napuniComboe() {
        jcomboIgrac.removeAllItems();

        toZahtev.setOperacija(Konstante.VRATI_KOSARKASE_IZ_JEDNOG_TIMA);
        toZahtev.setParametar(u.getDomacin());
        KlijentKomunikacija.getInstance().posaljiZahtev(toZahtev);
        try {
            toOdgovor = KlijentKomunikacija.getInstance().primiOdgovor();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FrmDodajUcinak.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (toOdgovor.getIzuzetak() != null) {
            try {
                throw (Exception) toOdgovor.getIzuzetak();
            } catch (Exception ex) {
                Logger.getLogger(FrmLogovanje.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        for (Kosarkas k : (List<Kosarkas>) toOdgovor.getRezultat()) {
            jcomboIgrac.addItem(k);
        }

        toZahtev.setOperacija(Konstante.VRATI_KOSARKASE_IZ_JEDNOG_TIMA);
        toZahtev.setParametar(u.getGost());
        KlijentKomunikacija.getInstance().posaljiZahtev(toZahtev);
        try {
            toOdgovor = KlijentKomunikacija.getInstance().primiOdgovor();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FrmDodajUcinak.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (toOdgovor.getIzuzetak() != null) {
            try {
                throw (Exception) toOdgovor.getIzuzetak();
            } catch (Exception ex) {
                Logger.getLogger(FrmLogovanje.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        for (Kosarkas k : (List<Kosarkas>) toOdgovor.getRezultat()) {
            jcomboIgrac.addItem(k);
        }

        napuniComboZaTipove();

        jcomboVrednost.removeAllItems();
        for (int i = 0; i < 100; i++) {
            jcomboVrednost.addItem(i);
        }
    }

    private void napuniTabelu() {
        TblModelUcinak tmu = new TblModelUcinak();
        jtblUcinci.setModel(tmu);

    }

    private void pozicionirajFormu() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    private void napuniComboZaTipove() {
        jcomboTip.removeAllItems();

        toZahtev.setOperacija(Konstante.VRATI_TIPOVE_UCINAKA);
        toZahtev.setParametar(null);
        KlijentKomunikacija.getInstance().posaljiZahtev(toZahtev);
        try {
            toOdgovor = KlijentKomunikacija.getInstance().primiOdgovor();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FrmDodajUcinak.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (toOdgovor.getIzuzetak() != null) {
            try {
                throw (Exception) toOdgovor.getIzuzetak();
            } catch (Exception ex) {
                Logger.getLogger(FrmLogovanje.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        for (TipUcinka tip : (List<TipUcinka>) toOdgovor.getRezultat()) {
            jcomboTip.addItem(tip);
        }
    }
}
