/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import komunikacija.KlijentKomunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;

/**
 *
 * @author Marko
 */
public class FrmDodajKorisnika extends javax.swing.JDialog {

    TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
    TransferObjekatOdgovor toOdgovor = new TransferObjekatOdgovor();

    /**
     * Creates new form FrmDodajKorisnika
     */
    public FrmDodajKorisnika(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pozicionirajFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jtxtMail = new javax.swing.JTextField();
        jtxtKI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnPotvrdi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtxtPass = new javax.swing.JPasswordField();
        jtxtPotvrda = new javax.swing.JPasswordField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos novog korisnika");

        jLabel1.setText("Unesite email adresu:");

        jLabel2.setText("Unesite korisničko ime:");

        jLabel3.setText("Unesite lozinku:");

        jLabel4.setText("Potvrdite lozinku:");

        jbtnPotvrdi.setText("Potvrdi");
        jbtnPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPotvrdiActionPerformed(evt);
            }
        });

        jButton2.setText("Resetuj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnPotvrdi))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(46, 46, 46)
                            .addComponent(jtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtKI, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                .addComponent(jtxtPass)
                                .addComponent(jtxtPotvrda)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtKI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtPotvrda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPotvrdi)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jtxtMail.setText("");
        jtxtKI.setText("");
        jtxtPass.setText("");
        jtxtPotvrda.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPotvrdiActionPerformed
        String mail = jtxtMail.getText().trim();
        String ki = jtxtKI.getText().trim();
        String pass = jtxtPass.getText().trim();
        String potvrda = jtxtPotvrda.getText().trim();

        if (validanUnos(mail, ki, pass, potvrda)) {
            Korisnik k = new Korisnik(ki, pass, mail);

            toZahtev.setOperacija(Konstante.VRATI_SVE_KORISNIKE);
            KlijentKomunikacija.getInstance().posaljiZahtev(toZahtev);
            try {
                toOdgovor = KlijentKomunikacija.getInstance().primiOdgovor();
            } catch (IOException ex) {
                Logger.getLogger(FrmDodajKorisnika.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmDodajKorisnika.class.getName()).log(Level.SEVERE, null, ex);
            }
            List<Korisnik> lk = (List<Korisnik>) toOdgovor.getRezultat();
            if (lk.contains(k)) {
                jtxtKI.setBorder(null);
                jtxtPass.setBorder(null);
                jtxtMail.setBorder(null);
                jtxtPotvrda.setBorder(null);
                jtxtKI.requestFocusInWindow();
                jtxtMail.setText("");
                jtxtKI.setText("");
                jtxtPass.setText("");
                jtxtPotvrda.setText("");
                JOptionPane.showMessageDialog(this, "Korisnik već postoji!", "Greška", JOptionPane.WARNING_MESSAGE);
                return;
            }

            toZahtev.setOperacija(Konstante.DODAJ_KORISNIKA);
            toZahtev.setParametar(k);
            KlijentKomunikacija.getInstance().posaljiZahtev(toZahtev);

            try {
                toOdgovor = KlijentKomunikacija.getInstance().primiOdgovor();
            } catch (IOException ex) {
                Logger.getLogger(FrmDodajKorisnika.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmDodajKorisnika.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (toOdgovor.getIzuzetak() != null) {
                try {
                    throw (Exception) toOdgovor.getIzuzetak();
                } catch (Exception ex) {
                    Logger.getLogger(FrmDodajKorisnika.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //Kontroler.getInstance().dodajKorisnika(k);
            JOptionPane.showMessageDialog(this, "Korisnik uspešno sačuvan!");
            this.dispose();
        }
    }//GEN-LAST:event_jbtnPotvrdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDodajKorisnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDodajKorisnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDodajKorisnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDodajKorisnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FrmDodajKorisnika dialog = new FrmDodajKorisnika(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton jbtnPotvrdi;
    private javax.swing.JTextField jtxtKI;
    private javax.swing.JTextField jtxtMail;
    private javax.swing.JPasswordField jtxtPass;
    private javax.swing.JPasswordField jtxtPotvrda;
    // End of variables declaration//GEN-END:variables

    private void pozicionirajFormu() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    private boolean validanUnos(String mail, String ki, String pass, String potvrda) {
        if (mail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti mail adresu!", "Greška!", JOptionPane.WARNING_MESSAGE);
            jtxtMail.setBorder(BorderFactory.createLineBorder(Color.RED));
            jtxtMail.requestFocusInWindow();
            return false;
        }

        if (!mail.contains("@")) {
            JOptionPane.showMessageDialog(this, "Mail adresa nije u odgovarajućem formatu, mora sadržati znak @!", "Greška!", JOptionPane.WARNING_MESSAGE);
            jtxtMail.setBorder(BorderFactory.createLineBorder(Color.RED));
            jtxtMail.requestFocusInWindow();
            return false;
        }

        if (ki.isEmpty() || ki.length() < 5) {
            JOptionPane.showMessageDialog(this, "Korisničko ime mora sadržati bar 5 karaktera!", "Greška!", JOptionPane.WARNING_MESSAGE);
            jtxtKI.setBorder(BorderFactory.createLineBorder(Color.RED));
            jtxtKI.requestFocusInWindow();
            jtxtMail.setBorder(null);
            return false;
        }

        if (pass.isEmpty() || pass.length() < 4) {
            JOptionPane.showMessageDialog(this, "Lozinka mora sadržati bar 4 karaktera!", "Greška!", JOptionPane.WARNING_MESSAGE);
            jtxtPass.setBorder(BorderFactory.createLineBorder(Color.RED));
            jtxtPass.requestFocusInWindow();
            jtxtMail.setBorder(null);
            jtxtKI.setBorder(null);
            return false;
        }

        if (!pass.equals(potvrda)) {
            JOptionPane.showMessageDialog(this, "Lozinke se ne poklapaju!", "Greška!", JOptionPane.WARNING_MESSAGE);
            jtxtPass.setBorder(BorderFactory.createLineBorder(Color.RED));
            jtxtPass.requestFocusInWindow();
            jtxtPotvrda.setBorder(BorderFactory.createLineBorder(Color.RED));
            jtxtMail.setBorder(null);
            jtxtKI.setBorder(null);
            return false;
        }

        return true;
    }

}
